services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: us-west2-docker.pkg.dev/nestjs-airbnb-448405/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: us-west2-docker.pkg.dev/nestjs-airbnb-448405/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: us-west2-docker.pkg.dev/nestjs-airbnb-448405/payments/production
    env_file:
      - ../apps/payments/.env
  notifications:
    image: us-west2-docker.pkg.dev/nestjs-airbnb-448405/notifications/production
    env_file:
      - ../apps/notifications/.env
  mongo:
    image: mongo

